/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BarzFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accountFacet"
      | "createAccount"
      | "defaultFallback"
      | "entryPoint"
      | "facetRegistry"
      | "getAddress"
      | "getBytecode"
      | "getCreationCode"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BarzDeployed"): EventFragment;

  encodeFunctionData(
    functionFragment: "accountFacet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultFallback",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryPoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "facetRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytecode",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreationCode",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accountFacet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultFallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryPoint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "facetRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBytecode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreationCode",
    data: BytesLike
  ): Result;
}

export namespace BarzDeployedEvent {
  export type InputTuple = [arg0: AddressLike];
  export type OutputTuple = [arg0: string];
  export interface OutputObject {
    arg0: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BarzFactory extends BaseContract {
  connect(runner?: ContractRunner | null): BarzFactory;
  waitForDeployment(): Promise<this>;

  interface: BarzFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accountFacet: TypedContractMethod<[], [string], "view">;

  createAccount: TypedContractMethod<
    [_verificationFacet: AddressLike, _owner: BytesLike, _salt: BigNumberish],
    [string],
    "nonpayable"
  >;

  defaultFallback: TypedContractMethod<[], [string], "view">;

  entryPoint: TypedContractMethod<[], [string], "view">;

  facetRegistry: TypedContractMethod<[], [string], "view">;

  getAddress: TypedContractMethod<
    [_verificationFacet: AddressLike, _owner: BytesLike, _salt: BigNumberish],
    [string],
    "view"
  >;

  getBytecode: TypedContractMethod<
    [
      _accountFacet: AddressLike,
      _verificationFacet: AddressLike,
      _entryPoint: AddressLike,
      _facetRegistry: AddressLike,
      _defaultFallback: AddressLike,
      _ownerPublicKey: BytesLike
    ],
    [string],
    "view"
  >;

  getCreationCode: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accountFacet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAccount"
  ): TypedContractMethod<
    [_verificationFacet: AddressLike, _owner: BytesLike, _salt: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "defaultFallback"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entryPoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "facetRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<
    [_verificationFacet: AddressLike, _owner: BytesLike, _salt: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBytecode"
  ): TypedContractMethod<
    [
      _accountFacet: AddressLike,
      _verificationFacet: AddressLike,
      _entryPoint: AddressLike,
      _facetRegistry: AddressLike,
      _defaultFallback: AddressLike,
      _ownerPublicKey: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreationCode"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BarzDeployed"
  ): TypedContractEvent<
    BarzDeployedEvent.InputTuple,
    BarzDeployedEvent.OutputTuple,
    BarzDeployedEvent.OutputObject
  >;

  filters: {
    "BarzDeployed(address)": TypedContractEvent<
      BarzDeployedEvent.InputTuple,
      BarzDeployedEvent.OutputTuple,
      BarzDeployedEvent.OutputObject
    >;
    BarzDeployed: TypedContractEvent<
      BarzDeployedEvent.InputTuple,
      BarzDeployedEvent.OutputTuple,
      BarzDeployedEvent.OutputObject
    >;
  };
}
